name: tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Go to test directory
        run: cd stubway.tests
      - name: Check directory
        run: pwd
      - name: Test with Maven
        run: mvn clean test
